version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "@eslint/js"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "tailwind-scrollbar"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "tailwindcss"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
